name: Release Creation

on:
  push:
    branches:
      - main
    paths:
      - 'module.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from module.json
        id: version
        run: echo "version=$(jq -r .version module.json)" >> $GITHUB_OUTPUT

      - name: Update download URL in module.json
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          jq ".download = \"https://github.com/${{ github.repository }}/releases/download/${TAG}/module.zip\"" module.json > temp.json && mv temp.json module.json

      - name: Create Zip
        run: zip -r ./module.zip module.json scripts/ styles/ templates/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.version.outputs.version }}"
          name: "v${{ steps.version.outputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json,./module.zip"
          allowUpdates: true